name: Unity Package CI
on:
  push:
    branches:
    - master
env:
    PKG_ROOT: ./
    PKG_BRANCH: upm
jobs:
  split-upm:
    name: Create upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git checkout -b "$PKG_BRANCH"
    - name: create samples~ folder
      run: |
        if [[ -d "Samples" ]]; then
          git mv Samples Samples~
          rm -f Samples.meta
        fi
        if [[ -d "Documentation" ]]; then
          git mv Documentation Documentation~
          rm -f Documentation.meta
        fi
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git commit -am "fix: Samples => Samples~ and Documentation => Documentation~"
        git push -f -u origin "$PKG_BRANCH"